"""Add Travel model for managing travel information

Revision ID: 1b6a3cb1f746
Revises: 3fa8a4ecca89
Create Date: 2024-12-16 15:28:37.387563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b6a3cb1f746'
down_revision = '3fa8a4ecca89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('country', postgresql.ENUM('한국', '미국', '유럽', name='country_types'), nullable=False))
        batch_op.add_column(sa.Column('region', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('budget_won', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('currency', postgresql.ENUM('KRW', 'USD', 'EUR', name='currency_types'), nullable=False))
        batch_op.add_column(sa.Column('budget_exchanged', sa.Integer(), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('budget_exchanged')
        batch_op.drop_column('currency')
        batch_op.drop_column('budget_won')
        batch_op.drop_column('region')
        batch_op.drop_column('country')
        batch_op.drop_column('travel_name')

    # ### end Alembic commands ###
